In [3]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("diabetes.csv")

In [6]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [7]:
df.corr()

Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.129459       0.141282      -0.081672   
Glucose                      0.129459  1.000000       0.152590       0.057328   
BloodPressure                0.141282  0.152590       1.000000       0.207371   
SkinThickness               -0.081672  0.057328       0.207371       1.000000   
Insulin                     -0.073535  0.331357       0.088933       0.436783   
BMI                          0.017683  0.221071       0.281805       0.392573   
DiabetesPedigreeFunction    -0.033523  0.137337       0.041265       0.183928   
Age                          0.544341  0.263514       0.239528      -0.113970   
Outcome                      0.221898  0.466581       0.065068       0.074752   

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.073535  0.017683                 -0.033523   
Glucose                   0.331357  0.221071                  0.137337   
BloodPressure             0.088933  0.281805                  0.041265   
SkinThickness             0.436783  0.392573                  0.183928   
Insulin                   1.000000  0.197859                  0.185071   
BMI                       0.197859  1.000000                  0.140647   
DiabetesPedigreeFunction  0.185071  0.140647                  1.000000   
Age                      -0.042163  0.036242                  0.033561   
Outcome                   0.130548  0.292695                  0.173844   

                               Age   Outcome  
Pregnancies               0.544341  0.221898  
Glucose                   0.263514  0.466581  
BloodPressure             0.239528  0.065068  
SkinThickness            -0.113970  0.074752  
Insulin                  -0.042163  0.130548  
BMI                       0.036242  0.292695  
DiabetesPedigreeFunction  0.033561  0.173844  
Age                       1.000000  0.238356  
Outcome                   0.238356  1.000000

In [8]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [9]:
X = df.iloc[0:,:-1].values
y = df.iloc[0:,-1].values

In [10]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [11]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [13]:
X = scaler.fit_transform(X)

In [14]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [15]:
X.shape

(768, 8)

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.8, random_state=24)

In [60]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Dropout

In [18]:
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=8))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])

In [19]:
model.fit(X_train, y_train, batch_size=32, epochs=100, validation_data=(X_test, y_test))

Epoch 1/100
5/5 [==============================] - 1s 63ms/step - loss: 0.6770 - accuracy: 0.5686 - val_loss: 0.7235 - val_accuracy: 0.5593
Epoch 2/100
5/5 [==============================] - 0s 24ms/step - loss: 0.6578 - accuracy: 0.6013 - val_loss: 0.7063 - val_accuracy: 0.5919
Epoch 3/100
5/5 [==============================] - 0s 15ms/step - loss: 0.6418 - accuracy: 0.6340 - val_loss: 0.6905 - val_accuracy: 0.6130
Epoch 4/100
5/5 [==============================] - 0s 24ms/step - loss: 0.6271 - accuracy: 0.6863 - val_loss: 0.6764 - val_accuracy: 0.6423
Epoch 5/100
5/5 [==============================] - 0s 15ms/step - loss: 0.6137 - accuracy: 0.7190 - val_loss: 0.6634 - val_accuracy: 0.6553
Epoch 6/100
5/5 [==============================] - 0s 24ms/step - loss: 0.5998 - accuracy: 0.7451 - val_loss: 0.6526 - val_accuracy: 0.6634
Epoch 7/100
5/5 [==============================] - 0s 17ms/step - loss: 0.5891 - accuracy: 0.7386 - val_loss: 0.6415 - val_accuracy: 0.6846
Epoch 8/100
5/5 [===

In [78]:
# 1. How to select appropriate optimizer.
# 2. How to select number of nodes in a layer.
# 3. How to select number of layers.
# 4. All in all one model.

In [20]:
pip install -U keras-tuner

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 kB 3.3 MB/s eta 0:00:00


In [21]:
import keras_tuner as kt

### How to select appropriate optimizer.

In [22]:
def build_model(hp):
  model = Sequential()

  model.add(Dense(32, activation='relu', input_dim=8))
  model.add(Dense(1, activation='sigmoid'))

  optimizer = hp.Choice('optimizer', values = ['adam', 'sgd', 'rmsprop', 'adadelta'])

  model.compile(optimizer = optimizer, loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [23]:
# tuner objext

tuner = kt.RandomSearch(build_model, objective='val_accuracy', max_trials=5)

In [24]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 4 Complete [00h 00m 02s]
val_accuracy: 0.5268292427062988

Best val_accuracy So Far: 0.6308943033218384
Total elapsed time: 00h 00m 10s


In [25]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

In [26]:
model = tuner.get_best_models(num_models=1)[0]

In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                288       
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 321 (1.25 KB)
Trainable params: 321 (1.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [28]:
model.fit(X_train, y_train, batch_size=32, epochs=100, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/100
5/5 [==============================] - 1s 73ms/step - loss: 0.6302 - accuracy: 0.7059 - val_loss: 0.6387 - val_accuracy: 0.6488
Epoch 8/100
5/5 [==============================] - 0s 26ms/step - loss: 0.6175 - accuracy: 0.7255 - val_loss: 0.6298 - val_accuracy: 0.6683
Epoch 9/100
5/5 [==============================] - 0s 16ms/step - loss: 0.6055 - accuracy: 0.7451 - val_loss: 0.6218 - val_accuracy: 0.6715
Epoch 10/100
5/5 [==============================] - 0s 26ms/step - loss: 0.5936 - accuracy: 0.7582 - val_loss: 0.6145 - val_accuracy: 0.6894
Epoch 11/100
5/5 [==============================] - 0s 17ms/step - loss: 0.5830 - accuracy: 0.7712 - val_loss: 0.6077 - val_accuracy: 0.7008
Epoch 12/100
5/5 [==============================] - 0s 17ms/step - loss: 0.5729 - accuracy: 0.7712 - val_loss: 0.6013 - val_accuracy: 0.7024
Epoch 13/100
5/5 [==============================] - 0s 29ms/step - loss: 0.5641 - accuracy: 0.7647 - val_loss: 0.5953 - val_accuracy: 0.7057
Epoch 14/100
5/5